apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dev-backend-g7
  name: g7
spec:
  ports:
  - name: http
    port: 9901
    protocol: TCP
    targetPort: 9901
  selector:
    app.kubernetes.io/instance: g7
    app.kubernetes.io/name: g7
  type: ClusterIP

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
#     service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
#     service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
#     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
#     service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-0cd264e85d3dd38cb
#     service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
#     service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
#     service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
#     service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "6"
#     service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#     service.beta.kubernetes.io/aws-load-balancer-type: external
#     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
#     service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing    
#     service.beta.kubernetes.io/aws-load-balancer-security-groups: sg-0cd264e85d3dd38cb
#     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-1:888018606814:certificate/28135dc4-b1ab-4530-a32f-9e61c3a0a22c
#     service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
#     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
#   name: g7
# spec:
#   ports:
#   - name: http
#     port: 10000
#     protocol: TCP
#     targetPort: 10000
#   selector:
#     app.kubernetes.io/instance: g7
#     app.kubernetes.io/name: g7
#   type: LoadBalancer