apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: color-service
  name: color-service
  namespace: dakota-infra
spec:
  ports:
  - name: http1
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http2
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: http3
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: color-service
status:
  loadBalancer: {}
