
# partners:
# - name: vendor-1
#   tls_auth: tls
#   hostname: vendor-1.gxs.com.sg
#   destination: partner-api.sgbank.dev 
#   dest_port: 443
# - name: vendor-2
#   tls_auth: mtls
#   hostname: vendor-2.gxs.com.sg
#   destination: api.sgbank.dev 
#   dest_port: 443

# cert:
#   generate_missing_cert: yes
partners:
- name: vendor-1
  tls_auth: tls
  hostname: localhost
  destination: localhost 
  dest_port: 8080
- name: vendor-2
  tls_auth: mtls
  hostname: localhost
  destination: localhost 
  dest_port: 8081
# - name: vendor-3
#   tls_auth: tls
#   hostname: localhost
#   destination: localhost 
#   dest_port: 8082
