apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: dev-backend-g7
  name: g7
spec:
  ports:
  - name: http
    nodePort: 30537
    port: 443
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: g7
    app.kubernetes.io/name: g7
  type: LoadBalancer
